/* Auto-generated by genmsg_cpp for file /home/alaina/ros/zagrosControl/msg/telo_state.msg */
#ifndef ZAGROSCONTROL_MESSAGE_TELO_STATE_H
#define ZAGROSCONTROL_MESSAGE_TELO_STATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace zagrosControl
{
template <class ContainerAllocator>
struct telo_state_ {
  typedef telo_state_<ContainerAllocator> Type;

  telo_state_()
  : remote_username()
  , battery_capacity(0.0)
  , power_state()
  , battery_low(false)
  , tell_remote_user()
  , phone_home()
  {
  }

  telo_state_(const ContainerAllocator& _alloc)
  : remote_username(_alloc)
  , battery_capacity(0.0)
  , power_state(_alloc)
  , battery_low(false)
  , tell_remote_user(_alloc)
  , phone_home(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _remote_username_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  remote_username;

  typedef float _battery_capacity_type;
  float battery_capacity;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _power_state_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  power_state;

  typedef uint8_t _battery_low_type;
  uint8_t battery_low;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tell_remote_user_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  tell_remote_user;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _phone_home_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  phone_home;


private:
  static const char* __s_getDataType_() { return "zagrosControl/telo_state"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b19c6fe489b2b2906e73c9577a122021"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string remote_username\n\
float32 battery_capacity\n\
string power_state\n\
bool battery_low\n\
string tell_remote_user\n\
string phone_home\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, remote_username);
    ros::serialization::serialize(stream, battery_capacity);
    ros::serialization::serialize(stream, power_state);
    ros::serialization::serialize(stream, battery_low);
    ros::serialization::serialize(stream, tell_remote_user);
    ros::serialization::serialize(stream, phone_home);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, remote_username);
    ros::serialization::deserialize(stream, battery_capacity);
    ros::serialization::deserialize(stream, power_state);
    ros::serialization::deserialize(stream, battery_low);
    ros::serialization::deserialize(stream, tell_remote_user);
    ros::serialization::deserialize(stream, phone_home);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(remote_username);
    size += ros::serialization::serializationLength(battery_capacity);
    size += ros::serialization::serializationLength(power_state);
    size += ros::serialization::serializationLength(battery_low);
    size += ros::serialization::serializationLength(tell_remote_user);
    size += ros::serialization::serializationLength(phone_home);
    return size;
  }

  typedef boost::shared_ptr< ::zagrosControl::telo_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zagrosControl::telo_state_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct telo_state
typedef  ::zagrosControl::telo_state_<std::allocator<void> > telo_state;

typedef boost::shared_ptr< ::zagrosControl::telo_state> telo_statePtr;
typedef boost::shared_ptr< ::zagrosControl::telo_state const> telo_stateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::zagrosControl::telo_state_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::zagrosControl::telo_state_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace zagrosControl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::zagrosControl::telo_state_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::zagrosControl::telo_state_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::zagrosControl::telo_state_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b19c6fe489b2b2906e73c9577a122021";
  }

  static const char* value(const  ::zagrosControl::telo_state_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb19c6fe489b2b290ULL;
  static const uint64_t static_value2 = 0x6e73c9577a122021ULL;
};

template<class ContainerAllocator>
struct DataType< ::zagrosControl::telo_state_<ContainerAllocator> > {
  static const char* value() 
  {
    return "zagrosControl/telo_state";
  }

  static const char* value(const  ::zagrosControl::telo_state_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::zagrosControl::telo_state_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string remote_username\n\
float32 battery_capacity\n\
string power_state\n\
bool battery_low\n\
string tell_remote_user\n\
string phone_home\n\
";
  }

  static const char* value(const  ::zagrosControl::telo_state_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::zagrosControl::telo_state_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.remote_username);
    stream.next(m.battery_capacity);
    stream.next(m.power_state);
    stream.next(m.battery_low);
    stream.next(m.tell_remote_user);
    stream.next(m.phone_home);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct telo_state_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zagrosControl::telo_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::zagrosControl::telo_state_<ContainerAllocator> & v) 
  {
    s << indent << "remote_username: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.remote_username);
    s << indent << "battery_capacity: ";
    Printer<float>::stream(s, indent + "  ", v.battery_capacity);
    s << indent << "power_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.power_state);
    s << indent << "battery_low: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.battery_low);
    s << indent << "tell_remote_user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tell_remote_user);
    s << indent << "phone_home: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.phone_home);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ZAGROSCONTROL_MESSAGE_TELO_STATE_H

